name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Check Maven build
        env:
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
        run: mvn --batch-mode --update-snapshots package
      - name: Run Maven tests
        env:
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
        run: mvn test